-- 账号目录：让系统内可以看到已建立的登录账号
-- Supabase > SQL Editor > New query > 粘贴整段 > Run

create table if not exists public.app_accounts (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_by text default '',
  created_at timestamptz not null default now()
);

alter table public.app_accounts enable row level security;

drop policy if exists "authenticated can read app accounts" on public.app_accounts;
drop policy if exists "authenticated can add app accounts" on public.app_accounts;

create policy "authenticated can read app accounts"
on public.app_accounts for select
to authenticated
using (true);

create policy "authenticated can add app accounts"
on public.app_accounts for insert
to authenticated
with check (true);

create index if not exists app_accounts_email_idx on public.app_accounts(email);
