-- 账号目录 + Admin/User 权限 + 停用/启用
-- User 可管理库存与提成、撤销单条库存记录，但不能删除整个饮料品项。
-- Admin 额外管理账号、产品类别，并可删除整个饮料。
-- Supabase > SQL Editor > New query > 粘贴整段 > Run

create table if not exists public.app_accounts (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null default 'user' check (role in ('admin','user')),
  is_active boolean not null default true,
  created_by text default '',
  created_at timestamptz not null default now()
);
alter table public.app_accounts add column if not exists role text not null default 'user';
alter table public.app_accounts add column if not exists is_active boolean not null default true;
alter table public.app_accounts drop constraint if exists app_accounts_role_check;
alter table public.app_accounts add constraint app_accounts_role_check check (role in ('admin','user'));
create or replace function public.current_app_role() returns text language sql stable security definer set search_path=public as $$ select coalesce((select role from public.app_accounts where lower(email)=lower(auth.jwt()->>'email') and is_active=true limit 1),'user'); $$;
create or replace function public.is_app_admin() returns boolean language sql stable security definer set search_path=public as $$ select public.current_app_role()='admin' and exists(select 1 from public.app_accounts where lower(email)=lower(auth.jwt()->>'email') and is_active=true); $$;
create or replace function public.is_app_active() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.app_accounts where lower(email)=lower(auth.jwt()->>'email') and is_active=true); $$;

alter table public.app_accounts enable row level security;
drop policy if exists "authenticated can read app accounts" on public.app_accounts; drop policy if exists "authenticated can add app accounts" on public.app_accounts; drop policy if exists "admin can read app accounts" on public.app_accounts; drop policy if exists "admin can add app accounts" on public.app_accounts; drop policy if exists "admin can update app accounts" on public.app_accounts; drop policy if exists "admin can delete app accounts" on public.app_accounts; drop policy if exists "user can read own app account" on public.app_accounts;
create policy "admin can read app accounts" on public.app_accounts for select to authenticated using (public.is_app_admin());
create policy "user can read own app account" on public.app_accounts for select to authenticated using (lower(email)=lower(auth.jwt()->>'email'));
create policy "admin can add app accounts" on public.app_accounts for insert to authenticated with check (public.is_app_admin() or (not exists(select 1 from public.app_accounts) and lower(email)=lower(auth.jwt()->>'email') and role='admin'));
create policy "admin can update app accounts" on public.app_accounts for update to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
create policy "admin can delete app accounts" on public.app_accounts for delete to authenticated using (public.is_app_admin());

alter table public.product_categories enable row level security;
drop policy if exists "authenticated can read categories" on public.product_categories; drop policy if exists "authenticated can add categories" on public.product_categories; drop policy if exists "authenticated can delete categories" on public.product_categories; drop policy if exists "admin can add categories" on public.product_categories; drop policy if exists "admin can delete categories" on public.product_categories;
create policy "authenticated can read categories" on public.product_categories for select to authenticated using (public.is_app_active());
create policy "admin can add categories" on public.product_categories for insert to authenticated with check (public.is_app_admin());
create policy "admin can delete categories" on public.product_categories for delete to authenticated using (public.is_app_admin());

-- 饮料品项：User 可新增/编辑及调整库存，但只有 Admin 能删除整个品项。
alter table public.inventory_items enable row level security;
drop policy if exists "authenticated can write inventory" on public.inventory_items; drop policy if exists "authenticated can read inventory" on public.inventory_items; drop policy if exists "authenticated can insert inventory" on public.inventory_items; drop policy if exists "authenticated can update inventory" on public.inventory_items; drop policy if exists "authenticated can delete inventory" on public.inventory_items; drop policy if exists "admin can insert inventory" on public.inventory_items; drop policy if exists "admin can delete inventory" on public.inventory_items;
create policy "authenticated can read inventory" on public.inventory_items for select to authenticated using (public.is_app_active());
create policy "authenticated can insert inventory" on public.inventory_items for insert to authenticated with check (public.is_app_active());
create policy "authenticated can update inventory" on public.inventory_items for update to authenticated using (public.is_app_active()) with check (public.is_app_active());
create policy "admin can delete inventory" on public.inventory_items for delete to authenticated using (public.is_app_admin());

-- 库存操作记录。
alter table public.inventory_logs enable row level security;
drop policy if exists "authenticated can read logs" on public.inventory_logs; drop policy if exists "authenticated can insert logs" on public.inventory_logs; drop policy if exists "authenticated can delete logs" on public.inventory_logs;
create policy "authenticated can read logs" on public.inventory_logs for select to authenticated using (public.is_app_active());
create policy "authenticated can insert logs" on public.inventory_logs for insert to authenticated with check (public.is_app_active());
-- 不再直接开放 DELETE；统一通过 undo_inventory_log 撤销，确保库存一起改回。

create or replace function public.undo_inventory_log(p_log_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  l public.inventory_logs%rowtype;
  i public.inventory_items%rowtype;
  q numeric;
  new_f numeric;
  new_w numeric;
begin
  if not public.is_app_active() then
    raise exception '此账号已停用';
  end if;

  select * into l from public.inventory_logs where id=p_log_id for update;
  if not found then raise exception '找不到这条库存记录'; end if;
  if l.item_id is null then raise exception '这条记录对应的饮料已经不存在，无法自动恢复库存'; end if;

  select * into i from public.inventory_items where id=l.item_id for update;
  if not found then raise exception '找不到对应饮料，无法恢复库存'; end if;

  q := coalesce(l.quantity,0);
  new_f := coalesce(i.fridge_quantity,0);
  new_w := coalesce(i.warehouse_quantity,0);

  if l.action='OUT' then
    if coalesce(l.note,'') like '冰箱｜%' then new_f := new_f + q;
    elsif coalesce(l.note,'') like '仓库｜%' then new_w := new_w + q;
    else raise exception '旧记录没有库存位置，无法自动恢复。请先手动盘点修正。';
    end if;
  elsif l.action='IN' then
    if coalesce(l.note,'') like '冰箱｜%' then
      if new_f < q then raise exception '当前冰箱库存不足以撤销这笔入库，请先检查后续记录'; end if;
      new_f := new_f - q;
    elsif coalesce(l.note,'') like '仓库｜%' then
      if new_w < q then raise exception '当前仓库库存不足以撤销这笔入库，请先检查后续记录'; end if;
      new_w := new_w - q;
    else raise exception '旧记录没有库存位置，无法自动恢复。请先手动盘点修正。';
    end if;
  elsif l.action='TRANSFER' then
    if coalesce(l.note,'') like '仓库 → 冰箱%' then
      if new_f < q then raise exception '当前冰箱库存不足以撤销这笔移库'; end if;
      new_f := new_f - q; new_w := new_w + q;
    elsif coalesce(l.note,'') like '冰箱 → 仓库%' then
      if new_w < q then raise exception '当前仓库库存不足以撤销这笔移库'; end if;
      new_w := new_w - q; new_f := new_f + q;
    else raise exception '无法识别这笔移库方向';
    end if;
  else
    raise exception '盘点、新增、编辑记录不能自动撤销库存，请用盘点功能修正';
  end if;

  update public.inventory_items
  set fridge_quantity=new_f, warehouse_quantity=new_w, quantity=new_f+new_w, updated_at=now()
  where id=i.id;

  delete from public.inventory_logs where id=p_log_id;
  return jsonb_build_object('ok',true,'fridge_quantity',new_f,'warehouse_quantity',new_w,'total',new_f+new_w);
end;
$$;

grant execute on function public.undo_inventory_log(bigint) to authenticated;

alter table public.commission_logs enable row level security;
drop policy if exists "authenticated can read commissions" on public.commission_logs; drop policy if exists "authenticated can insert commissions" on public.commission_logs; drop policy if exists "authenticated can delete commissions" on public.commission_logs; drop policy if exists "admin can delete commissions" on public.commission_logs;
create policy "authenticated can read commissions" on public.commission_logs for select to authenticated using (public.is_app_active());
create policy "authenticated can insert commissions" on public.commission_logs for insert to authenticated with check (public.is_app_active());
create policy "authenticated can delete commissions" on public.commission_logs for delete to authenticated using (public.is_app_active());
