const cfg=window.APP_CONFIG;
const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
const accountClient=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
let items=[],logs=[],commissions=[],categories=[],editingId=null,stockItemId=null,drawerItemId=null,realtimeChannel=null;
const $=id=>document.getElementById(id);
function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function fmt(v){return new Date(v).toLocaleString("zh-SG",{timeZone:"Asia/Singapore",hour12:false})}
function daySG(v){return new Date(v).toLocaleDateString("en-CA",{timeZone:"Asia/Singapore"})}
function todaySG(){return new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Singapore"})}
function userEmail(){return $("userEmail").textContent||""}
function fridge(x){return Number(x.fridge_quantity||0)}
function warehouse(x){return Number(x.warehouse_quantity||0)}
function total(x){return fridge(x)+warehouse(x)}
function showPage(page){const ids=["dashboard","inventory","commission","logs","settings"];ids.forEach(id=>{const el=document.getElementById(id);if(el)el.style.display=id===page?"block":"none"});document.querySelectorAll(".side-nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+page));window.scrollTo({top:0,behavior:"smooth"})}
function initSidebarNavigation(){document.querySelectorAll(".side-nav a").forEach(a=>{a.onclick=e=>{e.preventDefault();showPage(a.getAttribute("href").slice(1))}});showPage("dashboard")}
async function start(){if(!cfg||!cfg.SUPABASE_URL||cfg.SUPABASE_URL.includes("PASTE_")){ $("loginMsg").textContent="Supabase 设置未完成。";return }const{data:{session}}=await sb.auth.getSession();session?await showApp(session.user):showLogin();sb.auth.onAuthStateChange(async(_,s)=>s?await showApp(s.user):showLogin())}
function showLogin(){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden");$("logoutBtn").classList.add("hidden");$("userEmail").textContent=""}
async function showApp(user){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("logoutBtn").classList.remove("hidden");$("userEmail").textContent=user.email||"";ensureManagementUI();initSidebarNavigation();await loadAll();subscribeRealtime()}
async function login(){$("loginMsg").textContent="登录中...";const{error}=await sb.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});$("loginMsg").textContent=error?error.message:""}
async function logout(){await sb.auth.signOut()}
async function loadAll(){const[a,b,c,d]=await Promise.all([sb.from("inventory_items").select("*").order("name"),sb.from("inventory_logs").select("*").order("created_at",{ascending:false}).limit(80),sb.from("commission_logs").select("*").order("created_at",{ascending:false}).limit(100),sb.from("product_categories").select("*").order("name")]);if(a.error){alert("读取库存失败："+a.error.message);return}items=a.data||[];logs=b.error?[]:(b.data||[]);commissions=c.error?[]:(c.data||[]);categories=d.error?[]:(d.data||[]);render();renderCategoryManager();if(drawerItemId){const x=items.find(i=>i.id===drawerItemId);x?renderDrawer(x):closeItemDrawer()}}
function fillCategorySelect(selected){const el=$("itemCategory");if(!el)return;const names=categories.length?categories.map(x=>x.name):["汽水","果汁","矿泉水","茶饮","咖啡","运动饮料","其他"];el.innerHTML=names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join("");if(selected&&names.includes(selected))el.value=selected;else if(names.length)el.value=names[0]}
function render(){const q=$("search").value.trim().toLowerCase(),cat=$("categoryFilter").value;const shown=items.filter(x=>(!cat||x.category===cat)&&[x.name,x.category,x.spec,x.unit].join(" ").toLowerCase().includes(q));$("inventoryBody").innerHTML=shown.map(x=>{const t=total(x),low=t<=Number(x.min_quantity);return `<tr><td><button class="linkbtn" onclick="openItemDrawer('${x.id}')">${esc(x.name)}</button></td><td><span class="pill">${esc(x.category)}</span></td><td>${esc(x.spec||"")}</td><td>${esc(x.unit)}</td><td>${fridge(x)}</td><td>${warehouse(x)}</td><td class="${low?"low":"ok"}">${t}</td><td>${Number(x.min_quantity)}</td><td>$${Number(x.cost_price||0).toFixed(2)}</td><td class="money">$${Number(x.commission_per_unit||0).toFixed(2)}</td><td class="${low?"low":"ok"}">${low?"低库存":"正常"}</td><td class="actions"><button class="green" onclick="openStock('${x.id}','IN')">入库</button><button onclick="openStock('${x.id}','OUT')">出库</button><button class="secondary" onclick="openItemDrawer('${x.id}')">查看</button></td></tr>`}).join("")||`<tr><td colspan="12">暂无数据</td></tr>`;
$("logBody").innerHTML=logs.map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${esc(x.item_name)}</td><td>${({IN:"入库",OUT:"出库",ADJUST:"盘点",CREATE:"新增",EDIT:"编辑"}[x.action]||x.action)}</td><td>${Number(x.quantity||0)}</td><td>${esc(x.note||"")}</td><td>${esc(x.user_email||"")}</td></tr>`).join("")||`<tr><td colspan="6">暂无记录</td></tr>`;
$("commissionBody").innerHTML=commissions.map(x=>`<tr><td>${fmt(x.created_at)}</td><td><b>${esc(x.seller_name)}</b></td><td>${esc(x.item_name)}</td><td>${Number(x.quantity)}</td><td>$${Number(x.commission_per_unit||0).toFixed(2)}</td><td class="money">$${Number(x.commission_amount||0).toFixed(2)}</td><td>${esc(x.user_email||"")}</td></tr>`).join("")||`<tr><td colspan="7">暂无提成记录</td></tr>`;
$("statItems").textContent=items.length;$("statFridge").textContent=items.reduce((s,x)=>s+fridge(x),0).toFixed(0);$("statWarehouse").textContent=items.reduce((s,x)=>s+warehouse(x),0).toFixed(0);$("statQty").textContent=items.reduce((s,x)=>s+total(x),0).toFixed(0);$("statLow").textContent=items.filter(x=>total(x)<=Number(x.min_quantity)).length;$("statToday").textContent=logs.filter(x=>daySG(x.created_at)===todaySG()).length;$("statCommission").textContent="$"+commissions.filter(x=>daySG(x.created_at)===todaySG()).reduce((s,x)=>s+Number(x.commission_amount||0),0).toFixed(2);$("updatedAt").textContent="更新："+new Date().toLocaleTimeString("zh-SG",{hour12:false});const current=$("categoryFilter").value,cats=[...new Set(items.map(x=>x.category).filter(Boolean))].sort();$("categoryFilter").innerHTML=`<option value="">全部类别</option>`+cats.map(c=>`<option>${esc(c)}</option>`).join("");$("categoryFilter").value=current;const sellers=[...new Set(commissions.map(x=>x.seller_name).filter(Boolean))].sort();$("sellerList").innerHTML=sellers.map(s=>`<option value="${esc(s)}">`).join("")}
function newItem(){editingId=null;$("itemTitle").textContent="新增饮料";$("itemName").value="";fillCategorySelect();$("itemSpec").value="";$("itemUnit").value="瓶";$("itemFridgeQty").value=0;$("itemWarehouseQty").value=0;$("itemMin").value=5;$("itemCost").value=0;$("itemCommission").value=0;itemDialog.showModal()}
function editItem(id){const x=items.find(i=>i.id===id);if(!x)return;editingId=id;$("itemTitle").textContent="编辑饮料";$("itemName").value=x.name;fillCategorySelect(x.category);$("itemSpec").value=x.spec||"";$("itemUnit").value=x.unit;$("itemFridgeQty").value=fridge(x);$("itemWarehouseQty").value=warehouse(x);$("itemMin").value=x.min_quantity;$("itemCost").value=x.cost_price||0;$("itemCommission").value=x.commission_per_unit||0;itemDialog.showModal()}
async function saveItem(){const fq=Number($("itemFridgeQty").value||0),wq=Number($("itemWarehouseQty").value||0);const p={name:$("itemName").value.trim(),category:$("itemCategory").value,spec:$("itemSpec").value.trim(),unit:$("itemUnit").value.trim()||"瓶",fridge_quantity:fq,warehouse_quantity:wq,quantity:fq+wq,min_quantity:Number($("itemMin").value||0),cost_price:Number($("itemCost").value||0),commission_per_unit:Number($("itemCommission").value||0),updated_at:new Date().toISOString()};if(!p.name)return alert("请输入名称");const r=editingId?await sb.from("inventory_items").update(p).eq("id",editingId).select().single():await sb.from("inventory_items").insert(p).select().single();if(r.error)return alert("保存失败："+r.error.message);await sb.from("inventory_logs").insert({item_id:r.data.id,item_name:r.data.name,action:editingId?"EDIT":"CREATE",quantity:fq+wq,note:editingId?`编辑资料（冰箱 ${fq} / 仓库 ${wq}）`:`新增饮料（冰箱 ${fq} / 仓库 ${wq}）`,user_email:userEmail()});itemDialog.close();await loadAll()}
function toggleSeller(){const out=$("stockAction").value==="OUT";$("sellerWrap").classList.toggle("hidden",!out)}
function openStock(id,action){const x=items.find(i=>i.id===id);if(!x)return;stockItemId=id;$("stockTitle").textContent=x.name+" · 库存操作";$("stockAction").value=action;$("stockLocation").value=action==="OUT"?"fridge":"warehouse";$("stockQty").value="";$("stockSeller").value="";$("stockNote").value="";toggleSeller();stockDialog.showModal()}
async function saveStock(){const x=items.find(i=>i.id===stockItemId);if(!x)return;const action=$("stockAction").value,loc=$("stockLocation").value,qty=Number($("stockQty").value);if(!Number.isFinite(qty)||qty<0)return alert("请输入正确数量");const current=loc==="fridge"?fridge(x):warehouse(x);let next=current;if(action==="IN")next+=qty;if(action==="OUT"){if(qty>current)return alert((loc==="fridge"?"冰箱":"仓库")+"库存不足");next-=qty}if(action==="ADJUST")next=qty;const update=loc==="fridge"?{fridge_quantity:next,updated_at:new Date().toISOString()}:{warehouse_quantity:next,updated_at:new Date().toISOString()};const u=await sb.from("inventory_items").update(update).eq("id",x.id);if(u.error)return alert("库存更新失败："+u.error.message);const locationName=loc==="fridge"?"冰箱":"仓库";await sb.from("inventory_logs").insert({item_id:x.id,item_name:x.name,action,quantity:qty,note:`${locationName}｜${$("stockNote").value.trim()}`,user_email:userEmail()});if(action==="OUT"){const seller=$("stockSeller").value.trim();if(seller){const rate=Number(x.commission_per_unit||0);await sb.from("commission_logs").insert({item_id:x.id,item_name:x.name,seller_name:seller,quantity:qty,commission_per_unit:rate,commission_amount:qty*rate,user_email:userEmail()})}}stockDialog.close();await loadAll()}
function openItemDrawer(id){const x=items.find(i=>i.id===id);if(!x)return;drawerItemId=id;renderDrawer(x);$("drawerBackdrop").classList.remove("hidden");$("itemDrawer").classList.remove("hidden")}
function renderDrawer(x){const t=total(x),low=t<=Number(x.min_quantity);$("drawerName").textContent=x.name;$("drawerDetails").innerHTML=`<div class="detail-box"><small>类别</small><b>${esc(x.category)}</b></div><div class="detail-box"><small>规格</small><b>${esc(x.spec||"-")}</b></div><div class="detail-box"><small>冰箱库存</small><b>${fridge(x)}</b></div><div class="detail-box"><small>仓库库存</small><b>${warehouse(x)}</b></div><div class="detail-box"><small>总库存</small><b class="${low?"low":"ok"}">${t}</b></div><div class="detail-box"><small>最低库存</small><b>${Number(x.min_quantity)}</b></div><div class="detail-box"><small>成本价</small><b>$${Number(x.cost_price||0).toFixed(2)}</b></div><div class="detail-box"><small>每单位提成</small><b class="money">$${Number(x.commission_per_unit||0).toFixed(2)}</b></div>`;$("drawerInBtn").onclick=()=>{closeItemDrawer();openStock(x.id,"IN")};$("drawerOutBtn").onclick=()=>{closeItemDrawer();openStock(x.id,"OUT")};$("drawerEditBtn").onclick=()=>{closeItemDrawer();editItem(x.id)};$("drawerDeleteBtn").onclick=()=>deleteItem(x.id)}
function closeItemDrawer(){drawerItemId=null;$("drawerBackdrop").classList.add("hidden");$("itemDrawer").classList.add("hidden")}
async function deleteItem(id){const x=items.find(i=>i.id===id);if(!x)return;if(!confirm(`确定删除「${x.name}」吗？`))return;const r=await sb.from("inventory_items").delete().eq("id",id);if(r.error)return alert("删除失败："+r.error.message);closeItemDrawer();await loadAll()}
function ensureManagementUI(){const settings=document.getElementById("settings");if(!settings||document.getElementById("managementPanel"))return;const wrap=document.createElement("div");wrap.id="managementPanel";wrap.innerHTML=`<div style="height:14px"></div><div class="section-head"><h2>管理设置</h2></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px"><div style="border:1px solid #e5e7eb;border-radius:12px;padding:14px"><h3 style="margin:0 0 12px;font-size:16px">产品类别</h3><div style="display:flex;gap:8px"><input id="newCategoryName" placeholder="例如：气泡水" style="flex:1"><button id="addCategoryBtn">新增类别</button></div><div id="categoryManagerList" style="margin-top:12px"></div></div><div style="border:1px solid #e5e7eb;border-radius:12px;padding:14px"><h3 style="margin:0 0 12px;font-size:16px">新增登录账号</h3><input id="newAccountEmail" type="email" placeholder="员工 Email" style="width:100%;margin-bottom:8px"><input id="newAccountPassword" type="password" placeholder="初始密码（至少 6 位）" style="width:100%;margin-bottom:8px"><button id="createAccountBtn">新增账号</button><div id="accountCreateMsg" class="hint" style="margin-top:8px"></div></div></div>`;settings.appendChild(wrap);$("addCategoryBtn").onclick=addCategory;$("createAccountBtn").onclick=createAccount}
function renderCategoryManager(){const box=$("categoryManagerList");if(!box)return;if(!categories.length){box.innerHTML=`<div class="hint">请先运行 management-upgrade.sql</div>`;return}box.innerHTML=categories.map(c=>`<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;padding:7px 0;border-bottom:1px solid #eee"><span>${esc(c.name)}</span><button class="secondary" style="padding:5px 8px;font-size:12px" onclick="deleteCategory(${c.id},'${esc(c.name)}')">删除</button></div>`).join("")}
async function addCategory(){const input=$("newCategoryName"),name=input.value.trim();if(!name)return alert("请输入类别名称");const r=await sb.from("product_categories").insert({name,created_by:userEmail()});if(r.error)return alert("新增类别失败："+r.error.message+"\n请先运行 management-upgrade.sql");input.value="";await loadAll();fillCategorySelect()}
async function deleteCategory(id,name){if(items.some(x=>x.category===name))return alert("这个类别目前仍有产品使用，不能删除。请先把这些产品改到其他类别。");if(!confirm(`确定删除类别「${name}」吗？`))return;const r=await sb.from("product_categories").delete().eq("id",id);if(r.error)return alert("删除失败："+r.error.message);await loadAll()}
async function createAccount(){const email=$("newAccountEmail").value.trim(),password=$("newAccountPassword").value,msg=$("accountCreateMsg");if(!email)return alert("请输入 Email");if(password.length<6)return alert("密码至少 6 位");msg.textContent="建立中...";const{data,error}=await accountClient.auth.signUp({email,password});if(error){msg.textContent="建立失败："+error.message;return}$("newAccountEmail").value="";$("newAccountPassword").value="";msg.textContent=data.user?"账号已建立。若 Supabase 开启 Email Confirmation，员工需要先到邮箱确认后才能登录。":"已提交账号建立请求。"}
function subscribeRealtime(){if(realtimeChannel)sb.removeChannel(realtimeChannel);realtimeChannel=sb.channel("inventory-live").on("postgres_changes",{event:"*",schema:"public",table:"inventory_items"},()=>loadAll()).on("postgres_changes",{event:"*",schema:"public",table:"inventory_logs"},()=>loadAll()).on("postgres_changes",{event:"*",schema:"public",table:"commission_logs"},()=>loadAll()).on("postgres_changes",{event:"*",schema:"public",table:"product_categories"},()=>loadAll()).subscribe()}
$("loginBtn").onclick=login;$("logoutBtn").onclick=logout;$("addBtn").onclick=newItem;$("refreshBtn").onclick=loadAll;$("saveItemBtn").onclick=saveItem;$("saveStockBtn").onclick=saveStock;$("stockAction").onchange=toggleSeller;$("search").oninput=render;$("categoryFilter").onchange=render;start();