// 独立错单更正页面：集中查看品项错误与数量错误。
(function(){
  let installed=false,rows=[];
  function wait(){if(typeof sb==='undefined'||typeof showPage!=='function'||!document.querySelector('.side-nav')||!document.querySelector('.content-area')){setTimeout(wait,150);return;}install();}
  function install(){if(installed)return;installed=true;buildPage();extendNavigation();loadCorrections();}
  function buildPage(){const content=document.querySelector('.content-area');if(!content||document.getElementById('corrections'))return;const section=document.createElement('div');section.id='corrections';section.className='card panel-anchor';section.style.display='none';section.innerHTML=`<div class="section-head"><h2>错单更正</h2><span id="correctionCount" class="hint"></span></div><div id="correctionFilters" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;padding:12px;margin:8px 0 14px;border:1px solid #e5e7eb;border-radius:12px;background:#f8fafc"><label>开始日期<input id="correctionDateFrom" type="date"></label><label>结束日期<input id="correctionDateTo" type="date"></label><label>类型<select id="correctionTypeFilter"><option value="">全部类型</option><option value="item">品项错误</option><option value="quantity">数量错误</option></select></label><label>查找<input id="correctionKeyword" placeholder="饮料、备注或账号"></label><div style="display:flex;align-items:flex-end"><button id="resetCorrectionFilters" class="secondary" style="width:100%">重置</button></div></div><div class="tablewrap" style="max-height:70vh;overflow:auto"><table style="min-width:1050px"><thead><tr><th>日期</th><th>类型</th><th>饮料 / POS开成</th><th>实际 / 差异</th><th>调整</th><th>位置</th><th>备注</th><th>登记账号</th></tr></thead><tbody id="correctionHistoryBody"><tr><td colspan="8">读取中...</td></tr></tbody></table></div>`;content.appendChild(section);['correctionDateFrom','correctionDateTo','correctionTypeFilter'].forEach(id=>document.getElementById(id).onchange=renderRows);document.getElementById('correctionKeyword').oninput=renderRows;document.getElementById('resetCorrectionFilters').onclick=()=>{['correctionDateFrom','correctionDateTo','correctionTypeFilter','correctionKeyword'].forEach(id=>document.getElementById(id).value='');renderRows();};addStyle();}
  function extendNavigation(){const nav=document.querySelector('.side-nav');if(!nav)return;if(!nav.querySelector('a[href="#corrections"]')){const a=document.createElement('a');a.href='#corrections';a.innerHTML='<span class="side-icon">↺</span><span class="side-label">错单更正</span>';const settings=nav.querySelector('a[href="#settings"]');nav.insertBefore(a,settings||null);}const oldShowPage=showPage;showPage=function(page){const correction=document.getElementById('corrections');if(page==='corrections'){['dashboard','inventory','commission','logs','settings'].forEach(id=>{const el=document.getElementById(id);if(el)el.style.display='none';});if(correction)correction.style.display='block';document.querySelectorAll('.side-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#corrections'));window.scrollTo({top:0,behavior:'smooth'});loadCorrections();return;}if(correction)correction.style.display='none';oldShowPage(page);};document.querySelectorAll('.side-nav a').forEach(a=>{a.onclick=e=>{e.preventDefault();showPage(a.getAttribute('href').slice(1));};});}
  function dateOf(r){return r.operation_date||new Date(r.created_at).toLocaleDateString('en-CA',{timeZone:'Asia/Singapore'});}
  function locationOf(note){return String(note||'').startsWith('仓库｜')?'仓库':'冰箱';}
  function userNote(note){const parts=String(note||'').split('｜');const markers=['恢复误扣','补扣实际','恢复多扣','补扣少扣'];let idx=-1;for(const m of markers){const i=parts.indexOf(m);if(i>idx)idx=i;}if(idx>=0)return parts.slice(idx+1).join('｜');if(parts.includes('实际库存多')||parts.includes('实际库存少')){const diffIndex=parts.findIndex(x=>String(x).startsWith('差异 '));return diffIndex>=0?parts.slice(diffIndex+1).join('｜'):'';}return '';}
  function parseQuantity(list){const base=list[0],note=String(base.note||''),qty=Number(base.quantity||0),sign=base.action==='IN'?'+':'-';let actual='数量更正';if(note.includes('实际库存多'))actual=`实际库存多 ${qty}`;else if(note.includes('实际库存少'))actual=`实际库存少 ${qty}`;else{const pm=note.match(/POS 数量\s*([0-9.]+)/),am=note.match(/实际数量\s*([0-9.]+)/);if(pm&&am)actual=`POS ${Number(pm[1])} → 实际 ${Number(am[1])}`;}return {ref:String(base.correction_ref),date:dateOf(base),type:'quantity',primary:base.item_name||'',actual,adjust:`${sign}${qty}`,location:locationOf(base.note),note:userNote(base.note),user:base.user_email||'',created_at:base.created_at||''};}
  function parseItem(list){const wrong=list.find(r=>r.action==='IN'),actual=list.find(r=>r.action==='OUT'),base=wrong||actual||list[0],qty=Number((wrong||actual)?.quantity||0);return {ref:String(base.correction_ref),date:dateOf(base),type:'item',primary:wrong?.item_name||'',actual:actual?.item_name||'',adjust:wrong&&actual?`${wrong.item_name} +${qty} / ${actual.item_name} -${qty}`:`${base.item_name} ${base.action==='IN'?'+':'-'}${qty}`,location:wrong&&actual?`${locationOf(wrong.note)} / ${locationOf(actual.note)}`:locationOf(base.note),note:userNote(wrong?.note||actual?.note||''),user:base.user_email||'',created_at:base.created_at||''};}
  async function loadCorrections(){const body=document.getElementById('correctionHistoryBody');if(!body)return;body.innerHTML='<tr><td colspan="8">读取中...</td></tr>';const {data,error}=await sb.from('inventory_logs').select('*').not('correction_ref','is',null).order('operation_date',{ascending:false}).order('created_at',{ascending:false}).limit(2000);if(error){body.innerHTML=`<tr><td colspan="8">读取失败：${esc(error.message)}</td></tr>`;return;}const groups=new Map();(data||[]).forEach(r=>{const key=String(r.correction_ref);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);});rows=[...groups.values()].map(list=>list.some(r=>String(r.note||'').includes('｜数量错误｜'))?parseQuantity(list):parseItem(list)).sort((a,b)=>b.date.localeCompare(a.date)||String(b.created_at).localeCompare(String(a.created_at)));renderRows();}
  function renderRows(){const body=document.getElementById('correctionHistoryBody'),count=document.getElementById('correctionCount');if(!body)return;const from=document.getElementById('correctionDateFrom')?.value||'',to=document.getElementById('correctionDateTo')?.value||'',type=document.getElementById('correctionTypeFilter')?.value||'',kw=(document.getElementById('correctionKeyword')?.value||'').trim().toLowerCase();const filtered=rows.filter(r=>{if(from&&r.date<from)return false;if(to&&r.date>to)return false;if(type&&r.type!==type)return false;if(kw&&!([r.primary,r.actual,r.adjust,r.location,r.note,r.user,r.date].join(' ').toLowerCase().includes(kw)))return false;return true;});if(count)count.textContent=`${filtered.length} 条记录`;body.innerHTML=filtered.map(r=>`<tr><td>${esc(r.date)}</td><td><span class="pill">${r.type==='quantity'?'数量错误':'品项错误'}</span></td><td><b>${esc(r.primary)}</b></td><td>${esc(r.actual)}</td><td><b>${esc(r.adjust)}</b></td><td>${esc(r.location)}</td><td>${esc(r.note||'')}</td><td>${esc(r.user)}</td></tr>`).join('')||'<tr><td colspan="8">暂无错单更正记录</td></tr>';}
  function addStyle(){if(document.getElementById('correctionHistoryStyle'))return;const s=document.createElement('style');s.id='correctionHistoryStyle';s.textContent=`#correctionFilters label{font-size:12px;color:#667085;font-weight:600;display:flex;flex-direction:column;gap:6px}#correctionFilters input,#correctionFilters select{min-height:42px}#corrections table thead th{position:sticky;top:0;z-index:5;background:#f8fafc!important}#corrections tbody td{vertical-align:top}`;document.head.appendChild(s);}
  window.refreshCorrectionHistory=loadCorrections;wait();
})();