-- 产品类别管理升级
-- Supabase > SQL Editor > New query > 粘贴整段 > Run

create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_by text default '',
  created_at timestamptz not null default now()
);

alter table public.product_categories enable row level security;

drop policy if exists "authenticated can read categories" on public.product_categories;
drop policy if exists "authenticated can add categories" on public.product_categories;
drop policy if exists "authenticated can delete categories" on public.product_categories;

create policy "authenticated can read categories"
on public.product_categories for select
to authenticated
using (true);

create policy "authenticated can add categories"
on public.product_categories for insert
to authenticated
with check (true);

create policy "authenticated can delete categories"
on public.product_categories for delete
to authenticated
using (true);

insert into public.product_categories(name)
values ('汽水'),('果汁'),('矿泉水'),('茶饮'),('咖啡'),('运动饮料'),('其他')
on conflict (name) do nothing;

do $$
begin
  alter publication supabase_realtime add table public.product_categories;
exception
  when duplicate_object then null;
end $$;
