-- Supabase > SQL Editor > New query
-- 粘贴整段并 Run

create extension if not exists pgcrypto;

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null default '其他',
  spec text default '',
  unit text not null default '瓶',
  quantity numeric not null default 0 check (quantity >= 0),
  min_quantity numeric not null default 0 check (min_quantity >= 0),
  cost_price numeric not null default 0 check (cost_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_logs (
  id bigint generated by default as identity primary key,
  item_id uuid references public.inventory_items(id) on delete set null,
  item_name text not null,
  action text not null check (action in ('IN','OUT','ADJUST','CREATE','EDIT')),
  quantity numeric not null default 0,
  note text default '',
  user_email text default '',
  created_at timestamptz not null default now()
);

alter table public.inventory_items enable row level security;
alter table public.inventory_logs enable row level security;

drop policy if exists "authenticated can read inventory" on public.inventory_items;
drop policy if exists "authenticated can write inventory" on public.inventory_items;
drop policy if exists "authenticated can read logs" on public.inventory_logs;
drop policy if exists "authenticated can insert logs" on public.inventory_logs;

create policy "authenticated can read inventory"
on public.inventory_items for select
to authenticated
using (true);

create policy "authenticated can write inventory"
on public.inventory_items for all
to authenticated
using (true)
with check (true);

create policy "authenticated can read logs"
on public.inventory_logs for select
to authenticated
using (true);

create policy "authenticated can insert logs"
on public.inventory_logs for insert
to authenticated
with check (true);

-- 开启实时同步
alter publication supabase_realtime add table public.inventory_items;
alter publication supabase_realtime add table public.inventory_logs;

-- 可选：先放一些示例
insert into public.inventory_items(name,category,spec,unit,quantity,min_quantity,cost_price)
select * from (values
('Tiger Beer','啤酒','330ml','瓶',24,12,2.20),
('Coca-Cola','汽水','320ml','罐',36,12,0.80),
('Mineral Water','矿泉水','500ml','瓶',48,12,0.45),
('House Red Wine','红酒','750ml','瓶',8,3,15.00)
) as v(name,category,spec,unit,quantity,min_quantity,cost_price)
where not exists (select 1 from public.inventory_items);
