document.addEventListener('DOMContentLoaded',()=>{
  function setupTransfer(){
    if(document.getElementById('transferDialog'))return;
    const dialog=document.createElement('dialog');dialog.id='transferDialog';
    dialog.innerHTML=`<div class="modal"><h3 id="transferTitle">移库</h3><div class="grid2"><label>方向<select id="transferDirection"><option value="warehouse_to_fridge">仓库 → 冰箱</option><option value="fridge_to_warehouse">冰箱 → 仓库</option></select></label><label>数量<input id="transferQty" type="number" min="0.01" step="0.01"></label><label class="full">备注<input id="transferNote" placeholder="例如：补充冰箱库存"></label></div><div class="hint" style="margin-top:10px">移库只改变存放位置，总库存不变，也不会计算提成。</div><div class="modalfooter"><button class="secondary" id="cancelTransferBtn">取消</button><button id="saveTransferBtn">确认移库</button></div></div>`;
    document.body.appendChild(dialog);
    document.getElementById('cancelTransferBtn').onclick=()=>dialog.close();
    document.getElementById('saveTransferBtn').onclick=saveTransfer;
  }
  let transferItemId=null;
  window.openTransfer=function(id){const x=items.find(i=>i.id===id);if(!x)return;setupTransfer();transferItemId=id;document.getElementById('transferTitle').textContent=x.name+' · 移库';document.getElementById('transferDirection').value='warehouse_to_fridge';document.getElementById('transferQty').value='';document.getElementById('transferNote').value='';document.getElementById('transferDialog').showModal()};
  async function saveTransfer(){const x=items.find(i=>i.id===transferItemId);if(!x)return;const dir=document.getElementById('transferDirection').value,qty=Number(document.getElementById('transferQty').value),note=document.getElementById('transferNote').value.trim();if(!Number.isFinite(qty)||qty<=0)return alert('请输入大于 0 的移库数量');const f=Number(x.fridge_quantity||0),w=Number(x.warehouse_quantity||0);let nf=f,nw=w,label='';if(dir==='warehouse_to_fridge'){if(qty>w)return alert('仓库库存不足');nw=w-qty;nf=f+qty;label='仓库 → 冰箱'}else{if(qty>f)return alert('冰箱库存不足');nf=f-qty;nw=w+qty;label='冰箱 → 仓库'}const r=await sb.from('inventory_items').update({fridge_quantity:nf,warehouse_quantity:nw,quantity:nf+nw,updated_at:new Date().toISOString()}).eq('id',x.id);if(r.error)return alert('移库失败：'+r.error.message);await sb.from('inventory_logs').insert({item_id:x.id,item_name:x.name,action:'TRANSFER',quantity:qty,note:`${label}｜${note||'移库'}`,user_email:userEmail()});document.getElementById('transferDialog').close();await loadAll()}
  const oldRender=window.render;window.render=function(){oldRender();document.querySelectorAll('#inventoryBody tr').forEach(tr=>{const view=tr.querySelector('.actions button:last-child');if(!view||tr.querySelector('.transfer-btn'))return;const nameBtn=tr.querySelector('.linkbtn');if(!nameBtn)return;const m=(nameBtn.getAttribute('onclick')||'').match(/'([^']+)'/);if(!m)return;const b=document.createElement('button');b.className='secondary transfer-btn';b.textContent='移库';b.onclick=()=>openTransfer(m[1]);view.parentElement.insertBefore(b,view)})};
  const oldDrawer=window.renderDrawer;window.renderDrawer=function(x){oldDrawer(x);const actions=document.querySelector('.drawer-actions');if(actions&&!actions.querySelector('.transfer-btn')){const b=document.createElement('button');b.className='secondary transfer-btn';b.textContent='移库';b.onclick=()=>{closeItemDrawer();openTransfer(x.id)};actions.insertBefore(b,document.getElementById('drawerEditBtn'))}};
  setupTransfer();
});