// 界面优化：库存名称列可拖动调整宽度。
(function(){
  let inventoryNameWidth=Number(localStorage.getItem('inventoryNameWidth')||260),resizeReady=false;
  function text(sel,value){const el=document.querySelector(sel);if(el)el.textContent=value;}
  function attr(sel,name,value){const el=document.querySelector(sel);if(el)el.setAttribute(name,value);}
  function hideInventorySpec(){const table=document.querySelector('#inventory table');if(!table)return;const head=table.querySelector('thead tr');if(head&&head.children[2])head.children[2].style.display='none';table.querySelectorAll('tbody tr').forEach(tr=>{if(tr.children[2])tr.children[2].style.display='none';});applyInventoryWidth();setupInventoryResize();}
  function applyInventoryWidth(){inventoryNameWidth=Math.max(160,Math.min(650,inventoryNameWidth));const wrap=document.querySelector('#inventory .tablewrap');if(wrap)wrap.style.setProperty('--inventory-name-width',inventoryNameWidth+'px');}
  function setupInventoryResize(){if(resizeReady)return;const th=document.querySelector('#inventory table thead th:first-child');if(!th)return;resizeReady=true;th.style.position='sticky';const handle=document.createElement('span');handle.id='inventoryNameResize';handle.className='inventory-col-resizer';handle.title='拖动调整宽度';th.appendChild(handle);handle.addEventListener('mousedown',e=>{e.preventDefault();e.stopPropagation();const startX=e.clientX,startWidth=inventoryNameWidth;handle.classList.add('dragging');document.body.classList.add('resizing-column');const move=ev=>{inventoryNameWidth=startWidth+(ev.clientX-startX);applyInventoryWidth();};const up=()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up);handle.classList.remove('dragging');document.body.classList.remove('resizing-column');localStorage.setItem('inventoryNameWidth',String(inventoryNameWidth));};document.addEventListener('mousemove',move);document.addEventListener('mouseup',up);});}
  function polish(){document.title='饮料库存管理系统';text('header h1','饮料库存管理系统');text('header .subtitle','库存 · 调拨 · 销售提成');text('#loginView h2','系统登录');const loginP=document.querySelector('#loginView p:not(.msg)');if(loginP)loginP.textContent='请输入授权账号信息。';attr('#email','placeholder','账号 Email');attr('#search','placeholder','搜索名称、类别或规格');text('#inventory .section-head h2','库存明细');const commissionTitle=document.querySelector('#commission .section-head h2');if(commissionTitle)commissionTitle.textContent='销售提成';const status=document.getElementById('commissionStatus');if(status)status.textContent='';const sideBrand=document.querySelector('.side-brand b');if(sideBrand)sideBrand.textContent='库存管理';const sideSmall=document.querySelector('.side-brand small');if(sideSmall)sideSmall.textContent='BEVERAGE INVENTORY';document.querySelectorAll('.side-label').forEach(el=>{if(el.textContent.trim()==='员工提成')el.textContent='销售提成';});const note=document.querySelector('.side-note');if(note)note.remove();text('.danger-zone h3','删除饮料');const dangerP=document.querySelector('.danger-zone p');if(dangerP)dangerP.remove();text('#drawerDeleteBtn','删除');const commissionStat=document.getElementById('statCommission');if(commissionStat){const label=commissionStat.closest('.stat')?.querySelector('small');if(label)label.textContent='总提成';}hideInventorySpec();}
  function addStyle(){if(document.getElementById('uiPolishStyle'))return;const s=document.createElement('style');s.id='uiPolishStyle';s.textContent=`body{letter-spacing:.01em}.card{box-shadow:0 1px 3px rgba(15,23,42,.04)}button{font-weight:600}.sidebar{box-shadow:0 8px 24px rgba(0,0,0,.08)}th{font-weight:600}#inventory .tablewrap{max-height:calc(100vh - 230px);overflow:auto;position:relative;padding-top:0}#inventory table{border-collapse:separate;border-spacing:0;width:max-content;min-width:100%;table-layout:fixed}#inventory table thead{position:sticky;top:0;z-index:20}#inventory table thead th{position:sticky;top:0;z-index:21;background:#f8fafc!important;box-shadow:0 2px 0 #e5e7eb;padding-top:14px;padding-bottom:14px;min-width:95px}#inventory table th:first-child,#inventory table td:first-child{position:sticky;left:0;width:var(--inventory-name-width);min-width:var(--inventory-name-width);max-width:var(--inventory-name-width);background:#fff!important;box-shadow:2px 0 0 #e5e7eb}#inventory table tbody td:first-child{z-index:10;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#inventory table thead th:first-child{z-index:30;background:#f8fafc!important;overflow:visible}.inventory-col-resizer{position:absolute;right:-4px;top:0;width:9px;height:100%;cursor:col-resize;z-index:50}.inventory-col-resizer:hover,.inventory-col-resizer.dragging{background:rgba(24,57,87,.18)}body.resizing-column{cursor:col-resize;user-select:none}`;document.head.appendChild(s);}
  function run(){addStyle();polish();setInterval(hideInventorySpec,600);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();